### ISSUE TITLE
Severe building issues in the context of the latest node/npm

### ISSUE THREAD

**Issue by KnowledgeGarden** [szymonkaliski/cartographist#2]
I was able to compile this on an M1 Macbook Pro, but only after updating package.json  to reflect the latest Electron version.
Node version v16.15.0
After updating Electron, it would compile, but only display an empty window.

In this gist, I record what fails
https://gist.github.com/KnowledgeGarden/4fe40cbea486546b5544a7f8a7c90fd2

For the time being, I'm not sure where to go from here to make this a usable project; I have high hopes of doing so.

**Comment by szymonkaliski** [comment]
I was able to `npm install` and then `npm start` on a fresh pull on node v16.16.0, on a non-M1 Macbook.

I suspect forcing the update of Electron version is what broke it. I don't have a way to test on M1, but happy to accept a PR if you fix the issues after updating Electron.

**Comment by KnowledgeGarden** [comment]
Very interesting.
I've got it in vscode and will spend some cycles seeing if I can fix it. Thanks!
