### ISSUE TITLE
Any interest in keeping this project going if I do a PR?

### ISSUE THREAD

**Issue by GitMurf** [szymonkaliski/cartographist#3]
@szymonkaliski im an electron developer and been looking for a browser like the sounds of this! Curious if you are open to reviving this project? I’d be happy to put in significant contributions especially to get all the dependencies up to date and look at updating the build process to use vite and electron forge, add some GitHub actions etc.

But before I do, I wanted to check in to see if you think it’s worth it and if you’re open to adding a contributor / accepting PRs? Also curious where the project sits now? Is it operational for the most part?

Look forward to hearing from you!

**Comment by szymonkaliski** [comment]
Hey, this was just an experiment, I'm not "supporting" it in any way, feel free to make a fork if you want to work on this :) cheers!
